export const copy = {
  title: 'Nudge',
  loading: 'Loading...',
  retry: 'Retry',
  openFailed: 'Could not open Nudge. Close and try again.',
  signingIn: 'Signing in...',
  signInFailed: 'Could not sign in. Close and try again.',
  comingSoon: 'Mini App coming soon.',
  useTheBot: 'Use the bot for now.',
  waiting: 'Waiting on',
  received: 'Received',
  nothingWaiting: 'Nothing waiting. Send the bot a message to add one.',
  nothingReceived: 'Nothing received yet.',
  noDate: 'No date',
  overdue: 'Overdue',
  from: (who: string) => `from ${who}`,
  reminds: (when: string) => `Reminds ${when}`,
  receivedOn: (when: string) => `Received ${when}`,
  back: 'Back',
  whatLabel: 'What',
  fromLabel: 'From',
  expectedLabel: 'Expected',
  reminderLabel: 'Reminder',
  timesIn: (zone: string) => `Times in ${zone}`,
  save: 'Save',
  reopen: 'Reopen',
  setTimezoneFirst: 'Set a timezone first.',
  askTimezone: (zone: string) => `Set your timezone to ${zone}?`,
  deviceTimezone: (zone: string) => `Your device is in ${zone}.`,
  useTimezone: (zone: string) => `Use ${zone}`,
  keepTimezone: (zone: string) => `Keep ${zone}`,
  failed: 'Something went wrong. Try again.',
};
